backend:
  name: git-gateway
  branch: master
  auth_type: pkce
  app_id: a0c33b409daa8500b96dd0bb93adefbcfc92829dcddfece0a7290de99aaa7170

media_folder: static/img
public_folder: /img

site_url: https://cosmosdocs.io
logo_url: https://cosmosdocs.io/icon.png
locale: "fr"

slug:
  # Only accept 0-9, a-z, A-Z, _, -, ~
  encoding: "ascii"
  # Remove accent from identifier_fields(default to title)
  clean_accents: true
  # Replace unsafe characters
  sanitize_replacement: "-"

collections:
  - name: "cryptomonnaies"
    label: "Cryptomonnaies"
    label_singular: "Cryptomonnaie"
    description: "Liste des cryptomonnaies présentés sur le site Cosmosdocs.io"
    identifier_field: "title"
    folder: "content/cryptomonnaies"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "ncw-id", prefix: "cryptomonnaies", timestamp: false, hidden: false}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image"}
      - { label: "Logo dark mode", name: "darkLogo", widget: "image"}
      - { label: "Logo de la Navbar", name: "navbarLogo", widget: "image"}
      - { label: "Logo de la Navbar dark mode", name: "navbarDarkLogo", widget: "image"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Meta-Keywords", name: "metaKeywords", widget: "string"}
      - { label: "Lien du site officiel", name: "officialLink", widget: "string"}
      - { label: "Lien du site Twitter", name: "twitterLink", widget: "string"}
      - { label: "Lien du site Discord", name: "discordLink", widget: "string"}
      - { label: "Lien du site Medium", name: "mediumLink", widget: "string"}
  - name: "actualites"
    label: "Actualités"
    label_singular: "Actualité"
    description: "Liste des actualités présentés sur le site Cosmosdocs.io"
    identifier_field: "title"
    folder: "content/actualites"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "ncw-id", prefix: "actualites", timestamp: false, hidden: false}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Meta-Keywords", name: "metaKeywords", widget: "string"}
      - { label: "Cryptomonnaie", name: "cryptomonnaie", widget: "relation", collection: "cryptomonnaies", search_fields: ["title"], value_field: "title", multiple: true}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "airdrops"
    label: "Airdrops"
    label_singular: "Airdrop"
    description: "Liste des airdrops présentés sur le site Cosmosdocs.io"
    identifier_field: "title"
    folder: "content/airdrops"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "ncw-id", prefix: "airdrops", timestamp: false, hidden: false}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Meta-Keywords", name: "metaKeywords", widget: "string"}
      - { label: "Cryptomonnaie", name: "cryptomonnaie", widget: "relation", collection: "cryptomonnaies", search_fields: ["title"], value_field: "title", multiple: true}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "gouvernances"
    label: "Gouvernances"
    label_singular: "Gouvernance"
    description: "Liste des gouvernances présentés sur le site Cosmosdocs.io"
    identifier_field: "title"
    folder: "content/gouvernances"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "ncw-id", prefix: "gouvernances", timestamp: false, hidden: false}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Meta-Keywords", name: "metaKeywords", widget: "string"}
      - { label: "Cryptomonnaie", name: "cryptomonnaie", widget: "relation", collection: "cryptomonnaies", search_fields: ["title"], value_field: "title", multiple: true}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "staking"
    label: "Staking"
    label_singular: "Staking"
    description: "Liste des actualités présentés sur le site Cosmosdocs.io"
    identifier_field: "title"
    folder: "content/staking"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "ncw-id", prefix: "staking", timestamp: false, hidden: false}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Meta-Keywords", name: "metaKeywords", widget: "string"}
      - { label: "Cryptomonnaie", name: "cryptomonnaie", widget: "relation", collection: "cryptomonnaies", search_fields: ["title"], value_field: "title", multiple: true}
      - { label: "Body", name: "body", widget: "markdown" }