backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://cosmosdocs.io
logo_url: https://cosmosdocs.io/icon.png
locale: "fr"

slug:
  # Only accept 0-9, a-z, A-Z, _, -, ~
  encoding: "ascii"
  # Remove accent from identifier_fields(default to title)
  clean_accents: true
  # Replace unsafe characters
  sanitize_replacement: "-"

collections:
  - name: "cryptomonnaies"
    label: "Cryptomonnaies"
    label_singular: "Cryptomonnaie"
    description: "Liste des cryptomonnaies présentés sur le site Cosmosdocs.io"
    identifier_field: "title"
    folder: "content/cryptomonnaies"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image"}
      - { label: "Logo de la Navbar", name: "navbarLogo", widget: "image"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Meta-Keywords", name: "metaKeywords", widget: "string"}
      - { label: "Lien du site officiel", name: "officialLink", widget: "string"}
      - { label: "Lien du site Twitter", name: "twitterLink", widget: "string"}
      - { label: "Lien du site Discord", name: "discordLink", widget: "string"}
      - { label: "Lien du site Medium", name: "mediumLink", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }